// Mocks generated by Mockito 5.4.6 from annotations
// in flovi_driver/test/features/available_jobs/available_jobs_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flovi_driver/core/api/relocation_api.dart' as _i3;
import 'package:flovi_driver/core/models/relocation.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRelocation_0 extends _i1.SmartFake implements _i2.Relocation {
  _FakeRelocation_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RelocationApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelocationApi extends _i1.Mock implements _i3.RelocationApi {
  MockRelocationApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Relocation>> fetchPendingRelocations() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPendingRelocations,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Relocation>>.value(<_i2.Relocation>[]),
      ) as _i4.Future<List<_i2.Relocation>>);

  @override
  _i4.Future<List<_i2.Relocation>> fetchMyRelocations() => (super.noSuchMethod(
        Invocation.method(
          #fetchMyRelocations,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Relocation>>.value(<_i2.Relocation>[]),
      ) as _i4.Future<List<_i2.Relocation>>);

  @override
  _i4.Future<_i2.Relocation> bookRelocation(String? id) => (super.noSuchMethod(
        Invocation.method(
          #bookRelocation,
          [id],
        ),
        returnValue: _i4.Future<_i2.Relocation>.value(_FakeRelocation_0(
          this,
          Invocation.method(
            #bookRelocation,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Relocation>);
}
